"""
Orchestrator - reads all shared_state JSON files and uses Claude to synthesize
a structured weekly competitive intelligence briefing.

Outputs to stdout and writes shared_state/weekly_briefing.md.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import anthropic
from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel
from rich.rule import Rule

SHARED_STATE = Path(__file__).parent / "shared_state"
BRIEFING_FILE = SHARED_STATE / "weekly_briefing.md"
SAMPLE_DIR = SHARED_STATE / "sample"

MODEL = "claude-sonnet-4-6"

console = Console()

STATE_FILES = {
    "changelogs": SHARED_STATE / "changelogs.json",
    "job_postings": SHARED_STATE / "job_postings.json",
    "pricing": SHARED_STATE / "pricing.json",
    "social_signals": SHARED_STATE / "social_signals.json",
}

SAMPLE_FILES = {
    "changelogs": SAMPLE_DIR / "changelogs.json",
    "job_postings": SAMPLE_DIR / "job_postings.json",
    "pricing": SAMPLE_DIR / "pricing.json",
    "social_signals": SAMPLE_DIR / "social_signals.json",
}


def _load_state(use_sample: bool = False) -> dict[str, Any]:
    """Load all agent output files. Falls back to sample data if live data missing."""
    data: dict[str, Any] = {}
    file_map = SAMPLE_FILES if use_sample else STATE_FILES

    for key, path in file_map.items():
        if path.exists():
            try:
                data[key] = json.loads(path.read_text())
            except Exception as exc:
                console.print(f"  [yellow]Warning: could not parse {path}: {exc}[/yellow]")
                data[key] = {}
        else:
            # Try the other source as fallback
            fallback = SAMPLE_FILES[key] if not use_sample else STATE_FILES[key]
            if fallback.exists():
                console.print(f"  [yellow]{path.name} not found, using {'sample' if not use_sample else 'live'} fallback[/yellow]")
                try:
                    data[key] = json.loads(fallback.read_text())
                except Exception:
                    data[key] = {}
            else:
                console.print(f"  [red]No data for {key} (neither live nor sample)[/red]")
                data[key] = {}

    return data


def _build_prompt(state: dict[str, Any], run_date: str) -> str:
    # Serialize state as compact JSON for the prompt
    state_json = json.dumps(state, indent=2)

    return f"""You are a senior competitive intelligence analyst. Today is {run_date}.

You have been given structured data collected by four specialized scraping agents about our competitors.
Your task is to synthesize this data into a high-quality weekly competitive intelligence briefing.

## Collected Data

```json
{state_json}
```

## Output Format

Produce a Markdown document with exactly these sections. Be specific, cite data from the JSON,
and focus on actionable insights. Avoid filler phrases like "it's important to note".

# Weekly Competitive Intelligence Briefing
**Date:** {run_date}

## Executive Summary
2–4 bullet points capturing the most important developments this week across all competitors.
Focus on changes, not steady-state facts.

## Product & Changelog Highlights
For each competitor, summarize their most significant recent product updates.
Note velocity (how much shipped?) and strategic direction (what problems are they solving?).

## Hiring Signals & Strategic Bets
Analyze the job posting data. What departments are each competitor growing?
What does this signal about their 6–12 month strategic priorities?
Call out notable roles by name.

## Pricing Changes & Competitive Positioning
Report any price changes detected. Analyze the pricing structure:
are competitors moving up-market, bundling AI, or competing on price?
Flag implications for our own pricing strategy.

## Social & Market Sentiment
Summarize the social signals. What topics are generating the most engagement?
What narrative is each competitor pushing publicly?

## Recommended Actions
3–5 specific, actionable recommendations for our product/sales/marketing teams
based on this week's intelligence. Be concrete (e.g. "Accelerate X feature before Y ships").

---
*Generated by Competitive Intelligence Agent Fleet*
"""


def synthesize(use_sample: bool = False) -> str:
    """Load state, call Claude, return and save the briefing."""
    SHARED_STATE.mkdir(exist_ok=True)

    console.print(Rule("[bold cyan]Competitive Intelligence Orchestrator[/bold cyan]"))
    console.print(f"  Loading agent data (sample={use_sample})...\n")

    state = _load_state(use_sample=use_sample)
    run_date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # Count how many competitors appear across all datasets
    all_competitors: set[str] = set()
    for dataset in state.values():
        all_competitors.update(dataset.get("competitors", {}).keys())

    console.print(
        f"  Competitors found in state: [bold]{', '.join(sorted(all_competitors)) or 'none'}[/bold]\n"
        f"  Calling [bold cyan]{MODEL}[/bold cyan] to synthesize briefing...\n"
    )

    client = anthropic.Anthropic()
    prompt = _build_prompt(state, run_date)

    with console.status("[bold green]Generating briefing...[/bold green]"):
        response = client.messages.create(
            model=MODEL,
            max_tokens=4096,
            messages=[{"role": "user", "content": prompt}],
        )

    briefing = response.content[0].text

    # Save to file
    BRIEFING_FILE.write_text(briefing)
    console.print(f"  [green]Briefing written to {BRIEFING_FILE}[/green]\n")

    # Display with rich
    console.print(Rule("[bold cyan]Weekly Briefing[/bold cyan]"))
    console.print(Panel(Markdown(briefing), border_style="cyan", padding=(1, 2)))
    console.print(Rule())

    return briefing


if __name__ == "__main__":
    synthesize()
